# Generated by Django 4.2.7 on 2023-11-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
