# Generated by Django 4.2.7 on 2023-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answer_question_question_answers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
